version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    secrets:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports: ['9200:9200']
    networks: ['stack']
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  logstash:
    image: logstash-cloudwatch_logs:latest
    container_name: logstash
    command: --config.reload.automatic
    secrets:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash.yml
        target: /usr/share/logstash/config/logstash.yml
    healthcheck:
      test: bin/logstash --config.test_and_exit
      interval: 60s
      timeout: 50s
      retries: 1
    networks: ['stack']
    depends_on: ['elasticsearch']

secrets:
  logstash.yml:
    file: ./config/logstash/logstash.yml
  logstash.conf:
    file: ./config/logstash/pipeline/logstash.conf
  elasticsearch.yml:
    file: ./config/elasticsearch/elasticsearch.yml

networks: 
  stack:

volumes:
  es_data:
